/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TestImport } from './routes/test'
import { Route as DashboardImport } from './routes/dashboard'
import { Route as ControlImport } from './routes/control'
import { Route as BillingsImport } from './routes/billings'

// Create/Update Routes

const TestRoute = TestImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRoute = DashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const ControlRoute = ControlImport.update({
  id: '/control',
  path: '/control',
  getParentRoute: () => rootRoute,
} as any)

const BillingsRoute = BillingsImport.update({
  id: '/billings',
  path: '/billings',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/billings': {
      id: '/billings'
      path: '/billings'
      fullPath: '/billings'
      preLoaderRoute: typeof BillingsImport
      parentRoute: typeof rootRoute
    }
    '/control': {
      id: '/control'
      path: '/control'
      fullPath: '/control'
      preLoaderRoute: typeof ControlImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/billings': typeof BillingsRoute
  '/control': typeof ControlRoute
  '/dashboard': typeof DashboardRoute
  '/test': typeof TestRoute
}

export interface FileRoutesByTo {
  '/billings': typeof BillingsRoute
  '/control': typeof ControlRoute
  '/dashboard': typeof DashboardRoute
  '/test': typeof TestRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/billings': typeof BillingsRoute
  '/control': typeof ControlRoute
  '/dashboard': typeof DashboardRoute
  '/test': typeof TestRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/billings' | '/control' | '/dashboard' | '/test'
  fileRoutesByTo: FileRoutesByTo
  to: '/billings' | '/control' | '/dashboard' | '/test'
  id: '__root__' | '/billings' | '/control' | '/dashboard' | '/test'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  BillingsRoute: typeof BillingsRoute
  ControlRoute: typeof ControlRoute
  DashboardRoute: typeof DashboardRoute
  TestRoute: typeof TestRoute
}

const rootRouteChildren: RootRouteChildren = {
  BillingsRoute: BillingsRoute,
  ControlRoute: ControlRoute,
  DashboardRoute: DashboardRoute,
  TestRoute: TestRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/billings",
        "/control",
        "/dashboard",
        "/test"
      ]
    },
    "/billings": {
      "filePath": "billings.tsx"
    },
    "/control": {
      "filePath": "control.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard.tsx"
    },
    "/test": {
      "filePath": "test.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
